//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucky_Draw_Promotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.CodeQRs = new HashSet<CodeQR>();
            this.Gifts = new HashSet<Gift>();
        }
    
        public int MaCampaign { get; set; }
        public string CampaignName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Scanned { get; set; }
        public Nullable<int> UsedForSpin { get; set; }
        public Nullable<int> Winner { get; set; }
        public Nullable<bool> IsPartipate { get; set; }
        public string descriptionCA { get; set; }
        public string CampaignCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeQR> CodeQRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift> Gifts { get; set; }


        // thêm property ảo 
        // tạo dữ liệu
        public int CodeCount { get; set; }
        public int CodeLength { get; set; }
        public string Prefix { get; set; }
        public string Postfix { get; set; }

        public string StartDay { get; set; }
        public string EndDay { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}
