//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucky_Draw_Promotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeQR
    {
        public int MaCode { get; set; }
        public string NameCodeQR { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> usage { get; set; }
        public int QRCount { get; set; }
        public string image { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Scanned { get; set; }
        public int MaCampaign { get; set; }
        public int UserId { get; set; }
        public bool isWinPrize { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual userAccount userAccount { get; set; }
    }
}
